languageCode = "en-uk"
title = "Roland Johnson Transformations"
baseURL = "http://www.rjtransformations.co.uk"
theme = "hugo-freelancer-theme"

[[menu.main]]
  name = "About"
  url = "/index.html#about"
  weight = 1
[[menu.main]]
  name = "Packages"
  url = "/packages"
  weight = 2
[[menu.main]]
  name = "Testimonials"
  url = "/testimonials"
  weight = 3
[[menu.main]]
  name = "Videos"
  url = "/videos"
  weight = 4
[[menu.main]]
  name = "Contact"
  url = "/index.html#contact"
  weight = 5

[params]

  name = "RJ Transformations | Roland Johnson"
  description = "Roland Johnson personal trainer"

  email = "rjtransformations@outlook.com"

  # Custom assets
  custom_css = ["css/custom.css"]
  custom_js  = []

  [params.navigation]
    brand = "RJ Transformations"

  [params.header]
    subtitle = "Personal training and body transformations"

  [params.testimonial]
    title = "Testimonials"

  [params.videos]
    title = "My latest videos"
    youtube = []
    instagram = []

  [params.about]
    title = "About me"
    image = "img/about.jpg"
    paragraphs = [
      "Do you want to be leaner? Fitter? Stronger? I'm here to help you achieve your goals.",
      "Train with me and you'll push boundaries you didn't even know you had. I'll guide you through a series of positive changes that will stay with you for the long-term.",
      "Every session is fun and goal-orientated, leaving you knowing you've worked hard — and smart.",
      "I offer one-to-one training in Energie Fitness, Bethnal Green, and personalised online training and diet packages to clients around the world.",
      "Check out [what my clients say](/testimonials) and [get in touch](/index.html#contact) with me for a free consultation to start your journey."
    ]

  [params.contact]
    title = "Contact me"

    # 'error' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Name"
      error = "Please enter your name."

    [params.contact.form.email]
      text = "Email address"
      error = "Please enter your email address."

    [params.contact.form.phone]
      text = "Phone number (optional)"

    [params.contact.form.message]
      text = "Message"
      error = "Please enter a message."

    [params.contact.form.button]
      text = "Send"

  [params.footer]

    [params.footer.social]
      title = "Connect with me"

      [[params.footer.social.networks]]
        icon = "fa-instagram"
        link = "https://www.instagram.com/rjtransformations/"
