languageCode = "en-uk"
title = "Roland Johnson Transformations"
baseURL = "http://www.rjtransformations.co.uk/"
theme = "hugo-freelancer-theme"

[params]

  name = "RJ Transformations | Roland Johnson"
  description = "Roland Johnson personal trainer"

  email = "rjtransformations@outlook.com"

  # Custom assets
  custom_css = ["css/custom.css"]
  custom_js  = []

  [params.navigation]
    brand = "RJ Transformations"

  [params.header]
    subtitle = "Personal training and body transformations"

  [params.testimonial]
    title = "Testimonials"

  [params.videos]
    title = "My latest videos"
    youtube = []
    instagram = ["BISfT2KDjQp", "BI-Kz2wD1z0", "BNM39AsF9HR", "BL0yY9BlPv3"]

  [params.about]
    title = "About me"
    image = "img/about.jpg"
    paragraphs = [
      "I can help you make the transformation of your dreams. I'm an experienced personal trainer with a track record of helping people achieve their goals. Whether it's to bulk up, lose weight or get fit, I have tried-and-tested ways to get the best out of you.",
      "Check out my latest videos and some testimonials from clients below. If you're interested in a free, no-commitment introductory session then get in touch with me below."
    ]

  [params.contact]
    title = "Contact me"

    # 'error' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Name"
      error = "Please enter your name."

    [params.contact.form.email]
      text = "Email address"
      error = "Please enter your email address."

    [params.contact.form.phone]
      text = "Phone number (optional)"

    [params.contact.form.message]
      text = "Message"
      error = "Please enter a message."

    [params.contact.form.button]
      text = "Send"

  [params.footer]
    copyright = "Built by [Tom Barrett](//tbtommyb.github.io) | Powered by [Hugo](//gohugo.io)."

    [params.footer.social]
      title = "Connect with me"

      [[params.footer.social.networks]]
        icon = "fa-instagram"
        link = "https://www.instagram.com/rjtransformations/"
