backend:
  name: git-gateway
  branch: netlify
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
collections:
  - label: "Content"
    name: "content"
    files:
      - name: "testimonials"
        label: "Testimonials"
        file: "data/testimonials.yaml"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "img", widget: "image", required: false}
              - {label: "Text", name: "paras", widget: "markdown"}
      - name: "videos"
        label: "Videos"
        file: "data/videos.yaml"
        fields:
          - label: "Instagram"
            name: "instagram"
            widget: "list"
            required: false
            fields:
              - {label: "Video tag", name: "tag", widget: "string"}
          - label: "Youtube"
            name: "youtube"
            widget: "list"
            required: false
            fields:
              - {label: "Video tag", name: "tag", widget: "string"}
  - label: "Home page"
    name: "home"
    files:
      - name: "config"
        label: "Home page config"
        file: "config.toml"
        fields:
          - label: "languagecode"
            name: "Language code"
            widget: "hidden"
            default: "en-uk"
          - label: "title"
            name: "Title"
            widget: "string"
          - label: "baseurl"
            name: "Base URL"
            widget: "hidden"
            default: "https://www.rjtransformations.co.uk/"
          - label: "theme"
            name: "Theme"
            widget: "hidden"
            default: "hugo-freelancer-theme"
