backend:
  name: git-gateway
  branch: netlify
publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"
collections:
  - label: "Content"
    name: "content"
    files:
      - name: "testimonials"
        label: "Testimonials"
        file: "data/testimonials.yaml"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "img", widget: "image", required: false}
              - {label: "Text", name: "paras", widget: "markdown"}
